// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvbzegxcjgcgrhditznf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2YnplZ3hjamdjZ3JoZGl0em5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMTIxMDYsImV4cCI6MjA3MDY4ODEwNn0.GRJhISmeiVcNa8mMSDXeAJEt93IGfJhk9USW1IQR33w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});